<?xml version="1.0"?>
<robot name="macroed" xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:property name="wheel_radius" value="0.04" />
<xacro:property name="wheel_width" value="0.025" />

<xacro:property name="xyz" value="0 0 0"/>
<xacro:property name="rpy" value="0 0 0"/>
<xacro:property name="wheel_xyz" value="0 0 0"/>
<xacro:property name="wheel_rpy" value="0 0 0"/>
<xacro:property name="roller_xyz" value="0 .008 -.0465"/>
<xacro:property name="roller_rpy" value="0 ${-pi/12} 0"/>

<xacro:property name="roller_diameter" value="0.0055" />
<xacro:property name="roller_width" value="0.015" />

<!--offset from the center of the wheel for the rollers-->
<xacro:property name="roller_side_length" value=".0055"/>
<!--radius where the rollers are placed-->
<xacro:property name="roller_radius" value=".0465"/>

<material name="blue">
  <color rgba="0 0 .8 1"/>
</material>

<material name="grey">
  <color rgba=".18 .19 .19 1"/>
</material>

<material name="silver">
  <color rgba=".5176 .5294 .5373 1"/>
</material>


<material name="white">
  <color rgba="1 1 1 1"/>
</material>

<xacro:macro name="default_inertial" params="mass">
	<inertial>
     		<mass value="${mass}" />
	        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
            		           iyy="1.0" iyz="0.0" 
                                         izz="1.0" />
	</inertial>
</xacro:macro>

<link name="base_link">
    <visual>
        <geometry>
            <box size=".3048 .3048 .0254"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="silver"/>
    </visual>
    <collision>
        <geometry>
            <mesh filename="package://gazebosim/gazeboSimulation/models/VexRobot/chassis.dae"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <xacro:default_inertial mass="1"/>
</link>

<xacro:macro name="roller" params="prefix suffix theta side">
    <link name="${prefix}_roller_${suffix}">
        <visual>
            <geometry>
                <mesh filename="package://gazebosim/gazeboSimulation/models/VexRobot/Roller.stl"/>
            </geometry>
            <origin xyz="${roller_xyz}" rpy="${roller_rpy}"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://gazebosim/gazeboSimulation/models/VexRobot/Roller.stl"/>
            </geometry>
            <origin xyz="${roller_xyz}" rpy="${roller_rpy}"/>
        </collision>
        <xacro:default_inertial mass="1"/>
    </link>

    <joint name="joint_to_${prefix}_roller_${suffix}" type="continuous">
        <parent link="wheel_${prefix}"/>
        <child link="${prefix}_roller_${suffix}"/>
        <origin xyz="${roller_side_length*side} ${sin(theta)*roller_radius} ${cos(theta)*roller_radius}" rpy="${pi/2} ${theta} ${pi/2}"/>
    </joint>
</xacro:macro>

<xacro:macro name="wheel" params="prefix changeInX changeInY">
    <link name="wheel_${prefix}">
        <visual>
            <geometry>
                <mesh filename="package://gazebosim/gazeboSimulation/models/VexRobot/OmniWheelNoRollers.stl"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://gazebosim/gazeboSimulation/models/VexRobot/OmniWheelNoRollers.stl"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
        </collision>
        <xacro:default_inertial mass="1"/>
    </link>

    <joint name="joint_to_wheel_${prefix}" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_${prefix}"/>
        <origin xyz="${-changeInY} ${changeInX} 0" rpy="0 0 ${-pi/2}"/>
    </joint>

    <xacro:roller prefix="${prefix}" suffix="right_one" theta="${pi * ( 1/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_two" theta="${pi * ( 2/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_thr" theta="${pi * ( 3/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_for" theta="${pi * ( 4/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_fve" theta="${pi * ( 5/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_six" theta="${pi * ( 6/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_svn" theta="${pi * ( 7/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_ate" theta="${pi * ( 8/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_nne" theta="${pi * ( 9/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_ten" theta="${pi * (10/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_lvn" theta="${pi * (11/6)}" side="-1"/>
    <xacro:roller prefix="${prefix}" suffix="right_wlv" theta="${pi * (12/6)}" side="-1"/>

    <xacro:roller prefix="${prefix}" suffix="left_one" theta="${pi * ( 1/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_two" theta="${pi * ( 2/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_thr" theta="${pi * ( 3/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_for" theta="${pi * ( 4/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_fve" theta="${pi * ( 5/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_six" theta="${pi * ( 6/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_svn" theta="${pi * ( 7/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_ate" theta="${pi * ( 8/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_nne" theta="${pi * ( 9/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_ten" theta="${pi * (10/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_lvn" theta="${pi * (11/6) + ( pi / 12 )}" side="1"/>
    <xacro:roller prefix="${prefix}" suffix="left_wlv" theta="${pi * (12/6) + ( pi / 12 )}" side="1"/>
</xacro:macro>

<xacro:wheel prefix="front_right" changeInX=" .17145" changeInY=" .10145"/>
<xacro:wheel prefix="front_left " changeInX="-.17145" changeInY=" .10145"/>
<xacro:wheel prefix="back_right " changeInX=" .17145" changeInY="-.10145"/>
<xacro:wheel prefix="back_left  " changeInX="-.17145" changeInY="-.10145"/>


<!--


-->

</robot>
