<?xml version="1.0"?>
<robot name="macroed" xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:property name="wheel_radius" value="0.04" />
<xacro:property name="wheel_width" value="0.025" />
<xacro:property name="xyz" value="0 0 0"/>
<xacro:property name="rpy" value="1.5708 0 0"/>

<xacro:property name="roller_diameter" value="0.0055" />
<xacro:property name="roller_width" value="0.015" />

<material name="blue">
  <color rgba="0 0 0.8 1"/>
</material>

<material name="white">
  <color rgba="1 1 1 1"/>
</material>

<xacro:macro name="default_inertial" params="mass">
	<inertial>
     		<mass value="${mass}" />
	        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
            		           iyy="1.0" iyz="0.0" 
                                         izz="1.0" />
	</inertial>
</xacro:macro>

<link name="base_link">
    <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="${xyz}" rpy="${rpy}"/>
        <material name="blue"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="${xyz}" rpy="${rpy}"/>
    </collision>
    <xacro:default_inertial mass="1"/>
</link>

<!--offset from the center of the wheel for the rollers-->
<xacro:property name="roller_side_length" value=".0055"/>
<!--radius where the rollers are placed-->
<xacro:property name="roller_radius" value=".049"/>

<!--This is for all of the right rollers. I made a way to send theta to 
calculate the x, y, z, and pitch based off of parameters listed directly 
above-->
<xacro:macro name="right_roller" params="prefix theta">
    <link name="right_roller_${prefix}">
        <visual>
            <geometry>
              <cylinder radius="${roller_diameter}" length="${roller_width}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
              <cylinder radius="${roller_diameter}" length="${roller_width}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:default_inertial mass="1"/>
    </link>

    <joint name="joint_to_right_roller_${prefix}" type="continuous">
        <parent link="base_link"/>
        <child link="right_roller_${prefix}"/>
        <!--<origin xyz="0 0 0" rpy="0 0 0"/>-->
        <origin xyz="${sin(theta)*roller_radius} 0 ${cos(theta)*roller_radius}" rpy="0 ${theta + pi/2} 0"/><!---->
    </joint>
</xacro:macro>

<xacro:right_roller prefix="one" theta="${pi * ( 1/6)}"/>
<xacro:right_roller prefix="two" theta="${pi * ( 2/6)}"/>
<xacro:right_roller prefix="thr" theta="${pi * ( 3/6)}"/>
<xacro:right_roller prefix="for" theta="${pi * ( 4/6)}"/>
<xacro:right_roller prefix="fve" theta="${pi * ( 5/6)}"/>
<xacro:right_roller prefix="six" theta="${pi * ( 6/6)}"/>
<xacro:right_roller prefix="svn" theta="${pi * ( 7/6)}"/>
<xacro:right_roller prefix="ate" theta="${pi * ( 8/6)}"/>
<xacro:right_roller prefix="nne" theta="${pi * ( 9/6)}"/>
<xacro:right_roller prefix="ten" theta="${pi * (10/6)}"/>
<xacro:right_roller prefix="lvn" theta="${pi * (11/6)}"/>
<xacro:right_roller prefix="wlv" theta="${pi * (12/6)}"/>

-->

</robot>
